//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Boleteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boletos
    {
        public Boletos()
        {
            this.DetalleBoletos = new HashSet<DetalleBoletos>();
        }
    
        public byte idBoleto { get; set; }
        public decimal efectivoTotal { get; set; }
        public System.DateTime fechaEmision { get; set; }
        public byte cantidad { get; set; }
    
        public virtual Destinos Destinos { get; set; }
        public virtual TiposdeBoletos TiposdeBoletos { get; set; }
        public virtual ICollection<DetalleBoletos> DetalleBoletos { get; set; }
    }
}
