//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Boleteria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDBoleteriaEntities : DbContext
    {
        public BDBoleteriaEntities()
            : base("name=BDBoleteriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administradores> Administradores { get; set; }
        public DbSet<Boletos> Boletos { get; set; }
        public DbSet<Destinos> Destinos { get; set; }
        public DbSet<DetalleBoletos> DetalleBoletos { get; set; }
        public DbSet<Generos> Generos { get; set; }
        public DbSet<TiposdeBoletos> TiposdeBoletos { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
    }
}
