//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Boleteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposdeBoletos
    {
        public TiposdeBoletos()
        {
            this.Boletos = new HashSet<Boletos>();
        }
    
        public byte idTIpo { get; set; }
        public string tipodeBoleto { get; set; }
    
        public virtual ICollection<Boletos> Boletos { get; set; }
    }
}
