//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Boleteria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.DetalleBoletos = new HashSet<DetalleBoletos>();
        }
    
        public byte idUsuario { get; set; }
        public string primerNombre { get; set; }
        public string segundoNombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string genero { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string identidad { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<DetalleBoletos> DetalleBoletos { get; set; }
    }
}
